CREATE DATABASE [BD_Shop]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BD_Shop', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BD_Shop.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'@BD_Shop_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BD_Shop.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BD_Shop].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BD_Shop] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BD_Shop] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BD_Shop] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BD_Shop] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BD_Shop] SET ARITHABORT OFF 
GO

ALTER DATABASE [BD_Shop] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BD_Shop] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BD_Shop] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BD_Shop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BD_Shop] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BD_Shop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BD_Shop] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BD_Shop] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BD_Shop] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BD_Shop] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BD_Shop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BD_Shop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BD_Shop] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BD_Shop] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BD_Shop] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BD_Shop] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BD_Shop] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BD_Shop] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BD_Shop] SET  MULTI_USER 
GO

ALTER DATABASE [BD_Shop] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BD_Shop] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BD_Shop] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BD_Shop] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BD_Shop] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BD_Shop] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BD_Shop] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BD_Shop] SET  READ_WRITE 
GO

USE [BD_Shop]
GO

/****** Object:  Table [dbo].[Categories]    Script Date: 22.02.2021 13:29:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Categories](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NULL,
 CONSTRAINT [PK_Сategories] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[Products]    Script Date: 22.02.2021 13:29:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Products](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NULL,
	[Price] [decimal](18, 0) NULL,
	[Category_id] [int] NULL,
 CONSTRAINT [PK_Products12] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Products]  WITH CHECK ADD  CONSTRAINT [FK_Products_Сategories] FOREIGN KEY([Category_id])
REFERENCES [dbo].[Categories] ([Id])
GO

ALTER TABLE [dbo].[Products] CHECK CONSTRAINT [FK_Products_Сategories]
GO

INSERT INTO [dbo].[Categories]
           ([Name])
     VALUES
           ('Продукты'),
		   ('Хоз товары'),
		   ('Товары для животных')
GO

INSERT INTO [dbo].[Products]
           ([Name]
           ,[Price]
           ,[Category_id])
     VALUES
           ('Мыло', 150.0, 2),
		   ('Макароны', 50.0, 1),
		   ('Молоко', 70.0, 1)
GO